apply plugin: 'org.openjfx.javafxplugin'

sourceSets.main.java {
    srcDir 'src'
}

configurations {
    implementation.extendsFrom configurations.jsonlib
}

java {
  toolchain {
    // keep this pinned to java 17 for backwards compatibility even if we update to Java 25 in Chunky 2.6
    languageVersion = JavaLanguageVersion.of(17)
  }
}

javafx {
  version = '17'
  configuration = 'implementation'
  modules = ['javafx.base', 'javafx.controls', 'javafx.fxml']
}
